import type { AuditEvent, DriftItem, Simulation, User } from "./types";

export const DEPARTMENTS = [
  "Engineering",
  "Sales",
  "Finance",
  "IT",
  "People Ops",
  "Legal",
];

const RAW_GROUP_CATALOG = {
  Engineering: ["okta-eng-all", "gh-engineers", "aws-dev-readonly", "jira-contributors"],
  Sales: ["okta-sales-all", "salesforce-standard", "gong-users", "outreach-seats"],
  Finance: ["okta-fin-all", "netsuite-ap", "expensify-approvers", "bill-pay-review"],
  IT: ["okta-it-all", "okta-super-admin", "aws-prod-admin", "jamf-admins"],
  "People Ops": ["okta-hr-all", "workday-hr-partner", "greenhouse-recruiters"],
  Legal: ["okta-legal-all", "ironclad-editors", "docusign-senders"],
};

const RAW_APP_CATALOG = {
  Engineering: ["GitHub", "AWS", "Jira", "Datadog"],
  Sales: ["Salesforce", "Gong", "Outreach", "Zoom"],
  Finance: ["NetSuite", "Expensify", "Bill.com", "Zoom"],
  IT: ["Okta Admin", "AWS", "Jamf", "PagerDuty"],
  "People Ops": ["Workday", "Greenhouse", "Zoom"],
  Legal: ["Ironclad", "DocuSign", "Zoom"],
};

export const GROUP_CATALOG: Record<string, string[]> = RAW_GROUP_CATALOG;
export const APP_CATALOG: Record<string, string[]> = RAW_APP_CATALOG;

export const users: User[] = [
  {
    id: "usr_01",
    name: "Priya Raman",
    email: "priya.raman@northwind.io",
    title: "Staff Software Engineer",
    department: "Engineering",
    manager: "Dana Whitfield",
    location: "Bengaluru, IN",
    status: "ACTIVE",
    riskScore: 22,
    groups: [...RAW_GROUP_CATALOG.Engineering],
    apps: [...RAW_APP_CATALOG.Engineering],
    lastLogin: "2026-08-16T07:12:00Z",
    startDate: "2022-03-01",
  },
  {
    id: "usr_02",
    name: "Marcus Feld",
    email: "marcus.feld@northwind.io",
    title: "Director, Platform IT",
    department: "IT",
    manager: "Aisha Bello",
    location: "Austin, US",
    status: "ACTIVE",
    riskScore: 88,
    groups: [...RAW_GROUP_CATALOG.IT],
    apps: [...RAW_APP_CATALOG.IT],
    lastLogin: "2026-08-16T05:40:00Z",
    startDate: "2019-07-15",
  },
  {
    id: "usr_03",
    name: "Elena Vasquez",
    email: "elena.vasquez@northwind.io",
    title: "Enterprise AE",
    department: "Sales",
    manager: "Tom Nakamura",
    location: "Madrid, ES",
    status: "ACTIVE",
    riskScore: 34,
    groups: [...RAW_GROUP_CATALOG.Sales],
    apps: [...RAW_APP_CATALOG.Sales],
    lastLogin: "2026-08-15T18:02:00Z",
    startDate: "2023-01-09",
  },
  {
    id: "usr_04",
    name: "Samuel Okoye",
    email: "samuel.okoye@northwind.io",
    title: "Financial Analyst II",
    department: "Finance",
    manager: "Grace Lindqvist",
    location: "London, UK",
    status: "ACTIVE",
    riskScore: 46,
    groups: [...RAW_GROUP_CATALOG.Finance],
    apps: [...RAW_APP_CATALOG.Finance],
    lastLogin: "2026-08-16T08:55:00Z",
    startDate: "2021-11-02",
  },
  {
    id: "usr_05",
    name: "Hannah Brecht",
    email: "hannah.brecht@northwind.io",
    title: "Recruiting Lead",
    department: "People Ops",
    manager: "Aisha Bello",
    location: "Berlin, DE",
    status: "PENDING",
    riskScore: 12,
    groups: ["okta-hr-all"],
    apps: ["Workday"],
    lastLogin: "—",
    startDate: "2026-08-24",
  },
  {
    id: "usr_06",
    name: "Dana Whitfield",
    email: "dana.whitfield@northwind.io",
    title: "Engineering Manager",
    department: "Engineering",
    manager: "Aisha Bello",
    location: "Toronto, CA",
    status: "ACTIVE",
    riskScore: 51,
    groups: [...RAW_GROUP_CATALOG.Engineering, "aws-prod-admin"],
    apps: [...RAW_APP_CATALOG.Engineering, "PagerDuty"],
    lastLogin: "2026-08-16T06:30:00Z",
    startDate: "2020-02-17",
  },
  {
    id: "usr_07",
    name: "Tom Nakamura",
    email: "tom.nakamura@northwind.io",
    title: "VP Sales",
    department: "Sales",
    manager: "Aisha Bello",
    location: "Tokyo, JP",
    status: "ACTIVE",
    riskScore: 62,
    groups: [...RAW_GROUP_CATALOG.Sales, "netsuite-ap"],
    apps: [...RAW_APP_CATALOG.Sales, "NetSuite"],
    lastLogin: "2026-08-15T22:10:00Z",
    startDate: "2018-05-21",
  },
  {
    id: "usr_08",
    name: "Grace Lindqvist",
    email: "grace.lindqvist@northwind.io",
    title: "Controller",
    department: "Finance",
    manager: "Aisha Bello",
    location: "Stockholm, SE",
    status: "ACTIVE",
    riskScore: 71,
    groups: [...RAW_GROUP_CATALOG.Finance, "bill-pay-review"],
    apps: [...RAW_APP_CATALOG.Finance],
    lastLogin: "2026-08-16T04:18:00Z",
    startDate: "2017-09-11",
  },
  {
    id: "usr_09",
    name: "Owen Mbeki",
    email: "owen.mbeki@northwind.io",
    title: "SRE II",
    department: "Engineering",
    manager: "Dana Whitfield",
    location: "Cape Town, ZA",
    status: "SUSPENDED",
    riskScore: 79,
    groups: [...RAW_GROUP_CATALOG.Engineering, "aws-prod-admin"],
    apps: [...RAW_APP_CATALOG.Engineering],
    lastLogin: "2026-07-28T11:45:00Z",
    startDate: "2022-08-08",
  },
  {
    id: "usr_10",
    name: "清水 Aiko",
    email: "aiko.shimizu@northwind.io",
    title: "Legal Counsel",
    department: "Legal",
    manager: "Aisha Bello",
    location: "Osaka, JP",
    status: "ACTIVE",
    riskScore: 28,
    groups: [...RAW_GROUP_CATALOG.Legal],
    apps: [...RAW_APP_CATALOG.Legal],
    lastLogin: "2026-08-14T09:33:00Z",
    startDate: "2024-04-15",
  },
  {
    id: "usr_11",
    name: "Ravi Deshmukh",
    email: "ravi.deshmukh@northwind.io",
    title: "IT Support Specialist",
    department: "IT",
    manager: "Marcus Feld",
    location: "Pune, IN",
    status: "ACTIVE",
    riskScore: 55,
    groups: ["okta-it-all", "jamf-admins"],
    apps: ["Okta Admin", "Jamf"],
    lastLogin: "2026-08-16T03:05:00Z",
    startDate: "2023-06-19",
  },
  {
    id: "usr_12",
    name: "Chloe Bernard",
    email: "chloe.bernard@northwind.io",
    title: "Sales Development Rep",
    department: "Sales",
    manager: "Tom Nakamura",
    location: "Paris, FR",
    status: "ACTIVE",
    riskScore: 18,
    groups: ["okta-sales-all", "outreach-seats"],
    apps: ["Salesforce", "Outreach"],
    lastLogin: "2026-08-15T16:44:00Z",
    startDate: "2025-02-03",
  },
  {
    id: "usr_13",
    name: "Ibrahim Nasser",
    email: "ibrahim.nasser@northwind.io",
    title: "Data Engineer",
    department: "Engineering",
    manager: "Dana Whitfield",
    location: "Dubai, AE",
    status: "ACTIVE",
    riskScore: 41,
    groups: [...RAW_GROUP_CATALOG.Engineering],
    apps: [...RAW_APP_CATALOG.Engineering],
    lastLogin: "2026-08-16T02:22:00Z",
    startDate: "2024-10-07",
  },
  {
    id: "usr_14",
    name: "Nora Lindgren",
    email: "nora.lindgren@northwind.io",
    title: "AP Specialist",
    department: "Finance",
    manager: "Grace Lindqvist",
    location: "Helsinki, FI",
    status: "DEPROVISIONED",
    riskScore: 8,
    groups: [],
    apps: [],
    lastLogin: "2026-06-30T15:00:00Z",
    startDate: "2021-01-25",
  },
  {
    id: "usr_15",
    name: "Aisha Bello",
    email: "aisha.bello@northwind.io",
    title: "Chief Operating Officer",
    department: "People Ops",
    manager: "—",
    location: "Lagos, NG",
    status: "ACTIVE",
    riskScore: 67,
    groups: [...RAW_GROUP_CATALOG["People Ops"], "okta-super-admin"],
    apps: [...RAW_APP_CATALOG["People Ops"], "Okta Admin"],
    lastLogin: "2026-08-16T07:58:00Z",
    startDate: "2016-03-14",
  },
];

export const simulations: Simulation[] = [
  {
    id: "sim_4412",
    kind: "MOVER",
    subject: "Elena Vasquez",
    subjectEmail: "elena.vasquez@northwind.io",
    summary: "Sales → Finance transfer, effective Sep 01",
    risk: "HIGH",
    riskScore: 74,
    requiresApproval: true,
    status: "PENDING",
    createdAt: "2026-08-16T06:10:00Z",
    delta: {
      granted: ["okta-fin-all", "netsuite-ap", "expensify-approvers"],
      revoked: ["salesforce-standard", "gong-users", "outreach-seats"],
      unchanged: ["okta-mfa-enforced", "zoom-standard"],
    },
    impact: {
      groups: 6,
      apps: 4,
      privileged: 1,
      notes: [
        "netsuite-ap grants payment file visibility — SoD review required.",
        "Salesforce records reassign to Tom Nakamura on revoke.",
      ],
    },
  },
  {
    id: "sim_4409",
    kind: "LEAVER",
    subject: "Owen Mbeki",
    subjectEmail: "owen.mbeki@northwind.io",
    summary: "Involuntary termination, immediate deprovision",
    risk: "CRITICAL",
    riskScore: 91,
    requiresApproval: true,
    status: "PENDING",
    createdAt: "2026-08-16T05:02:00Z",
    delta: {
      granted: [],
      revoked: ["aws-prod-admin", "gh-engineers", "okta-eng-all", "jira-contributors"],
      unchanged: [],
    },
    impact: {
      groups: 4,
      apps: 4,
      privileged: 1,
      notes: [
        "Holds active AWS production admin session — force token revoke.",
        "3 on-call rotations require reassignment before deactivation.",
      ],
    },
  },
  {
    id: "sim_4401",
    kind: "JOINER",
    subject: "Hannah Brecht",
    subjectEmail: "hannah.brecht@northwind.io",
    summary: "New hire, Recruiting Lead — starts Aug 24",
    risk: "LOW",
    riskScore: 19,
    requiresApproval: false,
    status: "APPROVED",
    createdAt: "2026-08-15T14:20:00Z",
    delta: {
      granted: ["okta-hr-all", "workday-hr-partner", "greenhouse-recruiters"],
      revoked: [],
      unchanged: [],
    },
    impact: {
      groups: 3,
      apps: 3,
      privileged: 0,
      notes: ["Birthright bundle matched People Ops baseline with no exceptions."],
    },
  },
];

export const drift: DriftItem[] = [
  {
    id: "drf_881",
    user: "Dana Whitfield",
    userEmail: "dana.whitfield@northwind.io",
    entitlement: "aws-prod-admin",
    oktaState: "Assigned (direct)",
    policyState: "Not entitled for Engineering Manager",
    detectedAt: "2026-08-16T04:00:00Z",
    risk: "CRITICAL",
    riskScore: 93,
    status: "OPEN",
  },
  {
    id: "drf_877",
    user: "Tom Nakamura",
    userEmail: "tom.nakamura@northwind.io",
    entitlement: "netsuite-ap",
    oktaState: "Assigned (group)",
    policyState: "Requires Finance department",
    detectedAt: "2026-08-15T21:30:00Z",
    risk: "HIGH",
    riskScore: 78,
    status: "OPEN",
  },
  {
    id: "drf_863",
    user: "Ravi Deshmukh",
    userEmail: "ravi.deshmukh@northwind.io",
    entitlement: "jamf-admins",
    oktaState: "Assigned (direct)",
    policyState: "Time-bound grant expired Aug 12",
    detectedAt: "2026-08-13T09:12:00Z",
    risk: "MEDIUM",
    riskScore: 52,
    status: "OPEN",
  },
  {
    id: "drf_850",
    user: "Nora Lindgren",
    userEmail: "nora.lindgren@northwind.io",
    entitlement: "expensify-approvers",
    oktaState: "Removed",
    policyState: "Removed",
    detectedAt: "2026-07-01T10:00:00Z",
    risk: "LOW",
    riskScore: 11,
    status: "REMEDIATED",
  },
  {
    id: "drf_844",
    user: "Aisha Bello",
    userEmail: "aisha.bello@northwind.io",
    entitlement: "okta-super-admin",
    oktaState: "Assigned (direct)",
    policyState: "Approved exception — COO break-glass",
    detectedAt: "2026-06-20T08:00:00Z",
    risk: "HIGH",
    riskScore: 70,
    status: "IGNORED",
  },
];

export const auditEvents: AuditEvent[] = [
  {
    id: "aud_9931",
    at: "2026-08-16T07:59:00Z",
    actor: "automation@northwind.io",
    action: "SIMULATION_CREATED",
    target: "sim_4412 · Elena Vasquez",
    result: "SUCCESS",
    risk: "HIGH",
    detail: "Workday transfer event triggered mover simulation.",
  },
  {
    id: "aud_9927",
    at: "2026-08-16T05:03:00Z",
    actor: "marcus.feld@northwind.io",
    action: "LEAVER_ESCALATED",
    target: "sim_4409 · Owen Mbeki",
    result: "BLOCKED",
    risk: "CRITICAL",
    detail: "Auto-execute blocked: privileged session active in AWS prod.",
  },
  {
    id: "aud_9920",
    at: "2026-08-16T04:01:00Z",
    actor: "drift-scanner",
    action: "DRIFT_DETECTED",
    target: "drf_881 · aws-prod-admin",
    result: "SUCCESS",
    risk: "CRITICAL",
    detail: "Direct assignment outside policy baseline.",
  },
  {
    id: "aud_9911",
    at: "2026-08-15T14:22:00Z",
    actor: "automation@northwind.io",
    action: "JOINER_APPROVED",
    target: "sim_4401 · Hannah Brecht",
    result: "SUCCESS",
    risk: "LOW",
    detail: "Birthright bundle auto-approved under risk threshold 25.",
  },
  {
    id: "aud_9902",
    at: "2026-08-15T11:07:00Z",
    actor: "grace.lindqvist@northwind.io",
    action: "ACCESS_REQUEST_REJECTED",
    target: "req_2210 · bill-pay-review",
    result: "FAILED",
    risk: "MEDIUM",
    detail: "Separation-of-duties conflict with netsuite-ap.",
  },
  {
    id: "aud_9890",
    at: "2026-08-14T19:48:00Z",
    actor: "automation@northwind.io",
    action: "DRIFT_REMEDIATED",
    target: "drf_850 · expensify-approvers",
    result: "SUCCESS",
    risk: "LOW",
    detail: "Entitlement removed to match policy state.",
  },
  {
    id: "aud_9871",
    at: "2026-08-13T09:15:00Z",
    actor: "drift-scanner",
    action: "DRIFT_DETECTED",
    target: "drf_863 · jamf-admins",
    result: "SUCCESS",
    risk: "MEDIUM",
    detail: "Time-bound grant expired without revoke.",
  },
];
