/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as DriftRouteImport } from './routes/drift'
import { Route as JoinerRouteImport } from './routes/joiner'
import { Route as LeaverRouteImport } from './routes/leaver'
import { Route as MoverRouteImport } from './routes/mover'
import { Route as UsersRouteImport } from './routes/users'
import { Route as WhatifRouteImport } from './routes/whatif'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const DriftRoute = DriftRouteImport.update({
  id: '/drift',
  path: '/drift',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinerRoute = JoinerRouteImport.update({
  id: '/joiner',
  path: '/joiner',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaverRoute = LeaverRouteImport.update({
  id: '/leaver',
  path: '/leaver',
  getParentRoute: () => rootRouteImport,
} as any)
const MoverRoute = MoverRouteImport.update({
  id: '/mover',
  path: '/mover',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatifRoute = WhatifRouteImport.update({
  id: '/whatif',
  path: '/whatif',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/drift': typeof DriftRoute
  '/joiner': typeof JoinerRoute
  '/leaver': typeof LeaverRoute
  '/mover': typeof MoverRoute
  '/users': typeof UsersRoute
  '/whatif': typeof WhatifRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/drift': typeof DriftRoute
  '/joiner': typeof JoinerRoute
  '/leaver': typeof LeaverRoute
  '/mover': typeof MoverRoute
  '/users': typeof UsersRoute
  '/whatif': typeof WhatifRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/drift': typeof DriftRoute
  '/joiner': typeof JoinerRoute
  '/leaver': typeof LeaverRoute
  '/mover': typeof MoverRoute
  '/users': typeof UsersRoute
  '/whatif': typeof WhatifRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/drift'
    | '/joiner'
    | '/leaver'
    | '/mover'
    | '/users'
    | '/whatif'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/drift'
    | '/joiner'
    | '/leaver'
    | '/mover'
    | '/users'
    | '/whatif'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/drift'
    | '/joiner'
    | '/leaver'
    | '/mover'
    | '/users'
    | '/whatif'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  DriftRoute: typeof DriftRoute
  JoinerRoute: typeof JoinerRoute
  LeaverRoute: typeof LeaverRoute
  MoverRoute: typeof MoverRoute
  UsersRoute: typeof UsersRoute
  WhatifRoute: typeof WhatifRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drift': {
      id: '/drift'
      path: '/drift'
      fullPath: '/drift'
      preLoaderRoute: typeof DriftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joiner': {
      id: '/joiner'
      path: '/joiner'
      fullPath: '/joiner'
      preLoaderRoute: typeof JoinerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaver': {
      id: '/leaver'
      path: '/leaver'
      fullPath: '/leaver'
      preLoaderRoute: typeof LeaverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mover': {
      id: '/mover'
      path: '/mover'
      fullPath: '/mover'
      preLoaderRoute: typeof MoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatif': {
      id: '/whatif'
      path: '/whatif'
      fullPath: '/whatif'
      preLoaderRoute: typeof WhatifRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  DriftRoute: DriftRoute,
  JoinerRoute: JoinerRoute,
  LeaverRoute: LeaverRoute,
  MoverRoute: MoverRoute,
  UsersRoute: UsersRoute,
  WhatifRoute: WhatifRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
